vim.keymap.set('n', '<M-[>', ':tabprevious<CR>', { silent = true })
vim.keymap.set('n', '<M-]>', ':tabnext<CR>', { silent = true })
vim.keymap.set('n', '<leader>bd', ':bd<CR>', { silent = true, desc = 'Close current buffer' })
vim.keymap.set('n', '<leader>`', ':e #<CR>', { silent = true, desc = 'Switch to last buffer' })
vim.keymap.set('n', '<leader>cr', vim.lsp.buf.rename, { desc = 'Rename symbol' })
vim.keymap.set('n', 'D', vim.diagnostic.open_float, { desc = 'Show diagnostics in float' })
